SELECT DEP_RPT_GRP_SEVENTEEN,DEPT_SPECIALTY_NAME,DEPARTMENT_NAME,PROV_NAME_WID,DEPARTMENT_ID,REFERRING_PROV_NAME_WID,
                     MRN,PAT_NAME,ZIP_CODE,BIRTH_DATE,FINCLASS,
                     APPT_MADE_DTTM,APPT_DTTM,PRC_NAME,APPT_LENGTH,DERIVED_STATUS_DESC,
                     APPT_CANC_DTTM, CANCEL_REASON_NAME,
                     SIGNIN_DTTM,PAGED_DTTM,CHECKIN_DTTM,ARVL_LIST_REMOVE_DTTM,
                     ROOMED_DTTM,FIRST_ROOM_ASSIGN_DTTM,
                     PHYS_ENTER_DTTM,VISIT_END_DTTM,CHECKOUT_DTTM,
                     TIME_IN_ROOM_MINUTES,CYCLE_TIME_MINUTES,VIS_NEW_TO_DEP_YN,LOS_NAME,LOS_CODE,
                     DEP_RPT_GRP_THIRTYONE,APPT_ENTRY_USER_NAME_WID, 
                     ACCESS_CENTER_SCHEDULED_YN, VISIT_METHOD, VISIT_PROV_STAFF_RESOURCE_C,
                     PRIMARY_DX_CODE,ENC_CLOSED_CHARGE_STATUS,Y_ENC_COSIGN_TIME,Y_ENC_CLOSE_TIME,Y_ENC_OPEN_TIME, NPI, VISIT_GROUP_NUM
FROM CRREPORT_REP.MV_DM_PATIENT_ACCESS
WHERE CONTACT_DATE BETWEEN TO_DATE('2022-04-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
				AND TO_DATE('2022-04-19 23:59:59', 'YYYY-MM-DD HH24:MI:SS')
                     OR APPT_MADE_DTTM BETWEEN TO_DATE('2022-04-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
				AND TO_DATE('2022-04-19 23:59:59', 'YYYY-MM-DD HH24:MI:SS')